<a href="https://colab.research.google.com/github/sendyprstyo/Sendy_KC_TI1B/blob/main/OperasiMatematika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 02

# OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA

## Operasi matematika menggunakan python

In [4]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x, y)

5 18


In [5]:
x = abs(-7.25)
print(x)

7.25


In [6]:
import math
x = math.pow(4, 3)
print(x)

64.0


In [7]:
import math
x = math.sqrt(64)
print(x)

8.0


In [8]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x,y)

2 1


In [9]:
import math
x = math.pi
print(x)

3.141592653589793


## Menggunakan Fungsi MATH


In [ ]:
import math

# Trigonometri
angle_rad = math.radians(45)  # Konversi derajat ke radian
print("sin(45°) =", math.sin(angle_rad))
print("cos(45°) =", math.cos(angle_rad))
print("tan(45°) =", math.tan(angle_rad))

# Logaritma
print("\nlog(10) =", math.log(10))  # Logaritma natural (basis e)
print("log10(100) =", math.log10(100))  # Logaritma basis 10

# Konversi Radian ke Derajat
print("\n90 radian dalam derajat =", math.degrees(90))

# Jarak antara dua titik dalam 2D
point1 = (3, 4)
point2 = (7, 1)
print("\nJarak antara", point1, "dan", point2, "=", math.dist(point1, point2))

# Faktorial
print("\nFaktorial 5 =", math.factorial(5))

# Modulo (Sisa pembagian)
print("\n10.5 mod 3 =", math.fmod(10.5, 3))

# Cek apakah NaN (Not a Number)
print("\nCek apakah NaN:", math.isnan(float('nan')))

# Fungsi Gamma (umum dalam matematika statistik)
print("\nGamma(5) =", math.gamma(5))  # Harusnya hasilnya 4! = 24

# Permutasi (P(n, r) = n! / (n-r)!)
print("\nPermutasi 5P3 =", math.perm(5, 3))


sin(45°) = 0.7071067811865475
cos(45°) = 0.7071067811865476
tan(45°) = 0.9999999999999999

log(10) = 2.302585092994046
log10(100) = 2.0

90 radian dalam derajat = 5156.620156177409

Jarak antara (3, 4) dan (7, 1) = 5.0

Faktorial 5 = 120

10.5 mod 3 = 1.5

Cek apakah NaN: True

Gamma(5) = 24.0

Permutasi 5P3 = 60


## Operasi Matriks dan Vektor dengan python

In [ ]:
import numpy as np

# Operasi 1: Penjumlahan matriks
A1 = np.array([[80, 30, 25], [50, 20, 10]])
B1 = np.array([[30, 60, 15], [10, 30, 30]])
hasil_penjumlahan = A1 + B1
print("Hasil Penjumlahan Matriks:\n", hasil_penjumlahan)

# Operasi 2: Perkalian dot product
A2 = np.array([10, 20, 15])
B2 = np.array([16, 67, 35])
hasil_dot = np.dot(A2, B2)
print("\nHasil Dot Product:", hasil_dot)

# Operasi 3: Perkalian cross product
hasil_cross = np.cross(A2, B2)
print("\nHasil Cross Product:", hasil_cross)


Hasil Penjumlahan Matriks:
 [[110  90  40]
 [ 60  50  40]]

Hasil Dot Product: 2025

Hasil Cross Product: [-305 -110  350]


# Tugas Praktikum

In [11]:
import numpy as np

A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])

AxB = np.dot(A, B)
BxC = np.dot(B, C)

print("Matriks A:")
print(A)

print("\nMatriks B:")
print(B)

print("\nMatriks C:")
print(C)

print("\nHasil A × B:")
print(AxB)

print("\nHasil B × C:")
print(BxC)


Matriks A:
[[3 1]
 [2 0]]

Matriks B:
[[ 2  1]
 [ 1 -1]]

Matriks C:
[[-1  1  2]
 [ 2  0 -1]]

Hasil A × B:
[[7 2]
 [4 2]]

Hasil B × C:
[[ 0  2  3]
 [-3  1  3]]


In [12]:
import math

a = math.factorial(6)
b = math.factorial(8) / math.factorial(5)

print("a. 6! =", a)
print("b. 8! / 5! =", b)


a. 6! = 720
b. 8! / 5! = 336.0


In [13]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

dot_product = np.dot(A, B)

cross_product = np.cross(A, B)

print("Panjang Vektor A:", round(magnitude_A, 2))
print("Panjang Vektor B:", round(magnitude_B, 2))
print("\nHasil Perkalian Titik (A . B):", dot_product)
print("\nHasil Perkalian Silang (A × B):", cross_product)

Panjang Vektor A: 9.11
Panjang Vektor B: 12.41

Hasil Perkalian Titik (A . B): 58

Hasil Perkalian Silang (A × B): [ 24  79 -51]
